const {chromium}=require('/Users/elizabethstein/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base=process.env.REVIEW_URL||'http://127.0.0.1:5174';
const assert=require('node:assert/strict');const fs=require('fs');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});const c=await b.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});const p=await c.newPage();const passed=[];const errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.route('**/src/main.ts*',async route=>{const r=await route.fetch();await route.fulfill({response:r,body:(await r.text())+'\nwindow.__review={world,team,bag,crests,persist,makeCritter};'});});
await p.goto(base);await p.locator('.starter[data-id="tadmite"]').click();await p.locator('.title').waitFor({state:'detached'});assert.equal(await p.evaluate(()=>__review.team[0].species.id),'tadmite');passed.push('Choose Aqua starter; starter kit and local save created');
await p.reload();await p.waitForLoadState('networkidle');assert.equal(await p.locator('.title').count(),0);assert.equal(await p.evaluate(()=>__review.team[0].species.id),'tadmite');passed.push('Reload restores party without starter screen');
await p.evaluate(()=>{__review.team[0].hp=1;__review.world.setPos(-10,2.75)});await p.waitForTimeout(250);await p.keyboard.press('e');await p.locator('[data-act="rest"]').click();assert(await p.evaluate(()=>__review.team[0].hp===__review.team[0].maxHp));await p.keyboard.press('Escape');passed.push('Enter home from world; rest/heal/save; leave');
await p.evaluate(()=>__review.world.setPos(-6,14.75));await p.waitForTimeout(250);await p.keyboard.press('e');await p.locator('.shop-buy:not(:disabled)').first().click();await p.keyboard.press('Escape');passed.push('Enter Trading Post from world; purchase inventory; leave');
await p.evaluate(()=>__review.world.setPos(10,-11.25));await p.waitForTimeout(250);await p.keyboard.press('e');await p.locator('[data-act="summon"]').click();await p.locator('.summon-desc').fill('test draft');await p.keyboard.press('Escape');await p.waitForTimeout(200);await p.keyboard.press('e');await p.locator('[data-act="fuse"]').click();assert((await p.locator('.summon-sub').innerText()).includes('two critters'));await p.keyboard.press('Escape');await p.keyboard.press('Escape');passed.push('Enter lab; open/close summon and fusion empty state');
await p.evaluate(()=>{__review.world.active=false;Math.random=()=>0;__review.world.onEncounter({speciesId:'leaflet',level:3})});await p.waitForTimeout(700);await p.locator('#bag').click();await p.locator('[data-id="vale-ball"]').click();await p.locator('.battle').waitFor({state:'detached'});assert.equal(await p.evaluate(()=>__review.team.length),2);assert(await p.evaluate(()=>JSON.parse(localStorage.getItem('critter-vale-save-v1')).caughtIds.includes('leaflet')));passed.push('Wild encounter; ball capture; party/Dex/reward/save update');
await p.locator('.dexbtn').click();await p.locator('.dex-state').selectOption('caught');assert.equal(await p.locator('.dex-cell').count(),2);await p.keyboard.press('Escape');passed.push('Collection reflects newly caught creature');
await p.evaluate(()=>{__review.world.active=false;__review.world.onEncounter({speciesId:'emberpup',level:3})});await p.waitForTimeout(700);await p.locator('#run').click();await p.locator('.battle').waitFor({state:'detached'});passed.push('Wild run returns to overworld');
await p.evaluate(()=>__review.world.setPos(0,-16));await p.waitForTimeout(250);await p.keyboard.press('e');assert((await p.locator('.dialog').innerText()).includes('sealed'));await p.keyboard.press('Space');await p.keyboard.press('Space');assert.equal(await p.locator('.battle').count(),0);passed.push('Champion remains gated before three crests');
await p.evaluate(()=>{__review.team[0]=__review.makeCritter('torretoad',100);__review.team[1]=__review.makeCritter('emberwulf',100);__review.crests.add('Ember');__review.crests.add('Aqua');__review.crests.add('Leaf');__review.world.setPos(0,-16)});await p.waitForTimeout(200);await p.keyboard.press('e');while(await p.locator('.dialog').count())await p.keyboard.press('Space');
for(let i=0;i<20&&await p.locator('.battle').count();i++){const move=p.locator('.move').first();if(await move.isEnabled())await move.click();await p.waitForTimeout(1400);}
await p.locator('.victory').waitFor();await p.locator('.victory-btn').click();assert(await p.evaluate(()=>JSON.parse(localStorage.getItem('critter-vale-save-v1')).champion));passed.push('Three-crest fixture unlocks Champion; win, victory, continue and save');
p.once('dialog',d=>d.dismiss());await p.locator('.reset').click();
// No real user save is used; dismiss the reset confirmation in this isolated context.
assert.equal(errors.length,0);fs.writeFileSync('design-research/integration-journeys.json',JSON.stringify({passed,errors,fixtures:'Position placement, deterministic catch RNG, three crests and high-level Champion team are isolated fixtures; every UI action is clicked/typed.'},null,2));console.log(passed);await b.close();})().catch(e=>{console.error(e);process.exit(1)});
