const {chromium}=require('./pw.cjs');
const {AxeBuilder}=require('./tooling/node_modules/@axe-core/playwright');
const base=process.env.REVIEW_URL||'http://127.0.0.1:5174';
const fs=require('fs');const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});const results=[];const errors=[];
 for(const [device,width,height] of [['desktop',1440,960],['mobile',390,844]]){
  const context=await browser.newContext({viewport:{width,height},reducedMotion:'reduce'});const page=await context.newPage();
  page.on('pageerror',e=>errors.push({device,error:e.message}));
  await page.route('**/src/main.ts*',async route=>{const r=await route.fetch();await route.fulfill({response:r,body:(await r.text())+'\nwindow.__review={wallet,SUMMON_COST,world,team,openShop,showInterior,showFaintScreen,showVictory,drawHud,makeCritter,openSummonLab,openFusionLab,onSummoned,onFused,seen,caughtIds};'});});
  let mode='success';await page.route('**/api/summon*',async route=>{await new Promise(r=>setTimeout(r,250));await route.fulfill({status:mode==='error'?503:200,contentType:'application/json',body:JSON.stringify(mode==='error'?{error:'Test outage'}:route.request().method()==='POST'?{runId:'mock-run-1234567890'}:{status:'done',result:[base+'/sprites/emberpup.png']})});});
  const check=async(name,{shot=true}={})=>{await page.waitForTimeout(name==='battle'||name==='battle-trainer'?700:150);if(shot)await page.screenshot({path:`design-research/screenshots/integration/${name}-${device}.png`,fullPage:true});const audit=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();await page.bringToFront();results.push({device,name,violations:audit.violations.map(v=>({id:v.id,impact:v.impact,description:v.description,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})),horizontalOverflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)});};
  await page.goto(base);await page.waitForLoadState('networkidle');await check('title');
  await page.locator('.starter').first().click();await page.waitForTimeout(400);await check('overworld');
  const position=await page.evaluate(()=>__review.world.getPos());
  await page.locator('.guidebtn').click();await page.keyboard.down('d');await page.waitForTimeout(200);await page.keyboard.up('d');assert.deepEqual(await page.evaluate(()=>__review.world.getPos()),position,'movement must pause in guide');await page.keyboard.press('Escape');
  await page.waitForTimeout(250);assert(await page.locator('.guidebtn').evaluate(el=>el===document.activeElement),'guide must restore focus');
  await page.locator('.guidebtn').click();await check('guide');await page.keyboard.press('Escape');
  if(device==='mobile'){const box=await page.locator('[data-key="d"]').boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.waitForTimeout(250);await page.mouse.up();assert((await page.evaluate(()=>__review.world.getPos())).x>position.x,'touch must move player');}
  await page.locator('.dexbtn').click();await check('dex');await page.locator('.dex-search').pressSequentially('xyz');assert.equal(await page.locator('.dex').count(),1,'search x must not close collection');await check('dex-empty');await page.locator('.dex-reset').click();await page.locator('.dex-state').selectOption('caught');assert.equal(await page.locator('.dex-cell').count(),1);await check('dex-caught');await page.keyboard.press('Escape');
  await page.evaluate(()=>{__review.world.active=false;__review.openShop()});await check('shop');await page.locator('.shop-buy:not(:disabled)').first().click();await check('shop-purchased');await page.locator('.io-close').click();
  for(const kind of ['home','lab']){await page.evaluate(kind=>{__review.world.active=false;__review.showInterior({kind,name:kind==='home'?"Tamer's Home":'Critter Lab',color:0x5b8fd8})},kind);await check(kind);await page.locator('.io-close').click();}
  await page.evaluate(()=>{window.__testBalance=1000;window.__testWallet={balance:()=>__testBalance,spend:n=>{if(__testBalance<n)return false;__testBalance-=n;return true},refund:n=>{__testBalance+=n}};__review.openSummonLab(()=>{},__testWallet,60,()=>true)});await check('summon-full-party');assert(await page.locator('.summon-go').isDisabled());assert.equal(await page.evaluate(()=>__testBalance),1000);await page.keyboard.press('Escape');await page.evaluate(()=>__review.openSummonLab(()=>{},__testWallet,60,()=>false));await page.locator('.summon-name').fill('Testling');await page.locator('.summon-go').click();await check('summon-error');assert.equal(await page.locator('.summon-desc').getAttribute('aria-invalid'),'true');await page.locator('.summon-desc').fill('a little ember creature');mode='error';await page.locator('.summon-go').click();await check('summon-loading');await page.locator('[data-act="retry"]').waitFor();await check('summon-server-error');await page.locator('[data-act="retry"]').click();assert.equal(await page.locator('.summon-desc').inputValue(),'a little ember creature');mode='success';await page.locator('.summon-go').click();await page.locator('[data-act="add"]').waitFor();assert.equal(await page.locator('[data-act="add"]').innerText(),'Add to party');assert.equal(await page.evaluate(()=>__testBalance),940,'only successful generation stays charged');await check('summon-preview');await page.locator('[data-act="add"]').click();
  await page.evaluate(()=>__review.openFusionLab({party:__review.team,wallet:__testWallet,cost:80,onFused:()=>{}}));await check('fusion-empty');await page.keyboard.press('Escape');
  await page.evaluate(()=>__review.openFusionLab({party:[...__review.team,__review.makeCritter('tadmite',6)],wallet:__testWallet,cost:80,onFused:()=>{window.__kept=true}}));await check('fusion');await page.locator('.fusion-cell').nth(0).click();await page.locator('.fusion-cell').nth(1).click();await check('fusion-selected');mode='error';await page.locator('[data-act="fuse"]').click();await check('fusion-loading');await page.locator('[data-act="retry"]').waitFor();await check('fusion-error');await page.locator('[data-act="retry"]').click();assert.equal(await page.locator('.fusion-cell[aria-pressed="true"]').count(),2);mode='success';await page.locator('[data-act="fuse"]').click();await page.locator('[data-act="keep"]').waitFor();await check('fusion-preview');await page.locator('[data-act="keep"]').click();assert(await page.evaluate(()=>window.__kept));
  await page.evaluate(()=>__review.world.onInteract({name:'Prof. Hollis',lines:['Welcome to Sprout Hollow, tamer. Your adventure starts here.']}));await check('dialog');await page.keyboard.press('Space');
  const battle=async(trainer=false)=>page.evaluate(async trainer=>{__review.world.active=false;const {runBattle}=await import('/src/ui/battleUI.ts');window.__battleParty=[__review.makeCritter('emberpup',20),__review.makeCritter('tadmite',6)];__battleParty[1].hp=0;runBattle(__battleParty,[__review.makeCritter('leaflet',5)],outcome=>{window.__outcome=outcome},{bag:{'dew-potion':2,'vale-ball':4,revive:2},...(trainer?{trainerName:'Warden Pyra',restrict:{noSwitch:true,noItems:true}}:{})});},trainer);
  await battle();await check('battle');await page.locator('#bag').click();await check('battle-bag');await page.locator('[data-id="revive"]').click();await check('battle-revive');await page.locator('.switch-menu [data-i="1"]').click();await page.waitForTimeout(1100);assert(await page.evaluate(()=>__battleParty[1].hp>0));await page.locator('#switch').click();await check('battle-switch');await page.locator('.sw-cancel').click();await page.locator('.move').first().click();await page.waitForTimeout(1400);await check('battle-result');await page.waitForTimeout(1800);assert.equal(await page.evaluate(()=>window.__outcome),'won');
  await battle(true);await check('battle-trainer');assert(await page.locator('#bag').isHidden());assert(await page.locator('#switch').isHidden());assert(await page.locator('#run').isHidden());await page.locator('.move').first().click();await page.waitForTimeout(2100);
  await page.evaluate(()=>__review.showFaintScreen(()=>{}));await check('faint');await page.locator('.faint-btn').click();await page.evaluate(()=>__review.showVictory());await check('victory');
  await context.close();
 }
 fs.writeFileSync('design-research/integration-browser-verification.json',JSON.stringify({results,errors},null,2));await browser.close();console.log(JSON.stringify({screens:results.length,violations:results.filter(r=>r.violations.length).map(r=>({name:r.name,device:r.device,ids:r.violations.map(v=>v.id)})),errors},null,2));
})().catch(e=>{console.error(e);process.exit(1)});
